services:
  redis:
    image: bitnami/redis:7.4.1
    container_name: redis
    environment:
      - REDIS_PASSWORD=pass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  redis_data:
    driver: local
